-- Migration: team_members email uniqueness (run AFTER 20260826000000)
--
-- FIX: one person's email could end up on more than one team's
-- team_members roster (confirmed live: two real people each appear as a
-- member of two different teams in different pools), which is the root
-- cause of the dry-run bug where the Team Portal and Organiser/Judge
-- panels appeared to disagree on a person's pool — they were each
-- correctly reading a DIFFERENT team the same person was attached to.
--
-- ============================================================
-- STEP 1 — run this SELECT first and read the results. Do not skip this.
-- ============================================================
-- SELECT tm.id, tm.team_id, t.team_name, t.pool, tm.name, tm.email, tm.is_leader, tm.created_at
-- FROM public.team_members tm
-- JOIN public.teams t ON t.id = tm.team_id
-- WHERE lower(tm.email) IN (
--   SELECT lower(email) FROM public.team_members GROUP BY lower(email) HAVING COUNT(*) > 1
-- )
-- ORDER BY tm.email, tm.created_at;
--
-- As of 2026-08-26 this returns (at least) two collisions:
--   saivardhan1379@gmail.com — 3 rows, across "eclub test" (Pool A) and
--     "V2X" (Pool B)
--   ab25chb0b04@student.nitw.ac.in — 2 rows, across "Idk" and
--     "Archit's team"
--
-- ============================================================
-- STEP 2 — for each email the SELECT above returns, decide which ONE team
-- that person actually belongs to, then delete their team_members row(s)
-- on every OTHER team. Example (fill in the real ids from your STEP 1
-- results before running):
-- ============================================================
-- DELETE FROM public.team_members WHERE id = '<the row id to remove>';
--
-- If removing a row leaves a team with too few members to be valid (the
-- app enforces 2-4 members at registration time, but does not re-validate
-- an existing team after the fact), decide whether that team needs a
-- replacement member added back in, or whether the whole team should go
-- through the Data Management panel's delete-team flow instead.
--
-- ============================================================
-- STEP 3 — once the SELECT in Step 1 returns zero rows, run this:
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS team_members_email_unique
  ON public.team_members (lower(email));

-- If this still fails with a duplicate-key error, Step 1's SELECT missed a
-- collision (e.g. mixed casing) — re-run Step 1's query and repeat Step 2.
